title: Greg Pauloski
url: "https://gregpauloski.com"
baseurl: ""
google_analytics: G-G63Q9JW2W1

markdown: kramdown
#ins_logo: "./static/favicon.png"

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

favicon: yes
favicon_location: "static/favicon.png"

sass:
    style: compressed
    sass_dir: _sass

#nav:
# - name: "About"
#   link: "index"
# - name: "Contact"
#   link: "contact"

exclude:
 - README.md
 - LICENSE
 - pubs.bib
