name: check

on:
  push:
    branches: [test-me-*]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ubuntu-latest-pip-3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ubuntu-latest-pip-3.11-

      - name: Install Python Dependencies
        run: python -m pip install --upgrade setuptools pip

      - name: Install the Builder Package
        run: python -m pip install .

      - name: Verify static site builds
        run: python -m builder
