# Simple workflow for deploying static content to GitHub Pages
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: deploy

on:
  # Runs at 1am on Monday
  schedule:
    - cron: '00 1 * * 1'
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ubuntu-latest-pip-3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ubuntu-latest-pip-3.11-

      - name: Install Python Dependencies
        run: python -m pip install --upgrade setuptools pip

      - name: Install the Builder Package
        run: python -m pip install .

      - name: Build the static site
        run: python -m builder

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
